/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XvTE6NO331j
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'

import { useState } from 'react'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Button } from '@/components/ui/button'

export function createBlog() {
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [published, setPublished] = useState(false)
  const handlePublish = () => {
    setPublished(true)
  }
  return (
    <div className="px-4 py-6 md:px-6 lg:py-16 md:py-12">
      <article className="prose prose-gray mx-auto dark:prose-invert">
        <div className="flex flex-col items-start space-y-6">
          <div className="space-y-2">
            <Input
              placeholder="Title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
            <Textarea
              placeholder="Description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="min-h-[200px]"
            />
          </div>
          <Button
            onClick={handlePublish}
            className={`${
              published
                ? 'bg-green-500 text-green-50 hover:bg-green-600'
                : 'bg-primary text-primary-foreground hover:bg-primary/90'
            }`}
          >
            Publish
          </Button>
        </div>
      </article>
    </div>
  )
}
